# Generated by Django 3.1 on 2020-08-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200819_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('-name',)},
        ),
    ]
