# Generated by Django 3.1 on 2020-08-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200819_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='image',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
