# Generated by Django 3.1 on 2020-08-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_link_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
